spring.application.name=vinichy-shop
spring.sql.init.encoding=UTF-8

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:./database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Init (seed data)
spring.sql.init.mode=always
spring.sql.init.platform=sqlite
spring.jpa.defer-datasource-initialization=true

# Server Port
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Session
server.servlet.session.timeout=30m

# ===============================
# CẤU HÌNH EMAIL GỬI MÃ OTP TỰ ĐỘNG (AP thêm)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Điền email của bạn (email này sẽ làm nhiệm vụ gửi OTP cho khách)
spring.mail.username=anhphuong07062005@gmail.com
# Điền MẬT KHẨU ỨNG DỤNG (16 ký tự) của email trên, không phải mật khẩu đăng nhập bình thường nha!
spring.mail.password=mugjlidgidafxpet
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


